/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLogoutRouteImport } from './routes/_app/logout'
import { Route as AppAuthedRouteImport } from './routes/_app/_authed'
import { Route as AppAuthedGuideRouteImport } from './routes/_app/_authed/guide'
import { Route as AppAuthedProjectsIndexRouteImport } from './routes/_app/_authed/projects.index'
import { Route as AppAuthedProjectsRecentsRouteImport } from './routes/_app/_authed/projects.recents'
import { Route as AppAuthedProjectsNameRouteImport } from './routes/_app/_authed/projects.$name'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLogoutRoute = AppLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedGuideRoute = AppAuthedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedProjectsIndexRoute = AppAuthedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedProjectsRecentsRoute =
  AppAuthedProjectsRecentsRouteImport.update({
    id: '/projects/recents',
    path: '/projects/recents',
    getParentRoute: () => AppAuthedRoute,
  } as any)
const AppAuthedProjectsNameRoute = AppAuthedProjectsNameRouteImport.update({
  id: '/projects/$name',
  path: '/projects/$name',
  getParentRoute: () => AppAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/update-password': typeof UpdatePasswordRoute
  '/logout': typeof AppLogoutRoute
  '/guide': typeof AppAuthedGuideRoute
  '/projects/$name': typeof AppAuthedProjectsNameRoute
  '/projects/recents': typeof AppAuthedProjectsRecentsRoute
  '/projects/': typeof AppAuthedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/update-password': typeof UpdatePasswordRoute
  '/logout': typeof AppLogoutRoute
  '/guide': typeof AppAuthedGuideRoute
  '/projects/$name': typeof AppAuthedProjectsNameRoute
  '/projects/recents': typeof AppAuthedProjectsRecentsRoute
  '/projects': typeof AppAuthedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_app/_authed': typeof AppAuthedRouteWithChildren
  '/_app/logout': typeof AppLogoutRoute
  '/_app/_authed/guide': typeof AppAuthedGuideRoute
  '/_app/_authed/projects/$name': typeof AppAuthedProjectsNameRoute
  '/_app/_authed/projects/recents': typeof AppAuthedProjectsRecentsRoute
  '/_app/_authed/projects/': typeof AppAuthedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/update-password'
    | '/logout'
    | '/guide'
    | '/projects/$name'
    | '/projects/recents'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/update-password'
    | '/logout'
    | '/guide'
    | '/projects/$name'
    | '/projects/recents'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/update-password'
    | '/_app/_authed'
    | '/_app/logout'
    | '/_app/_authed/guide'
    | '/_app/_authed/projects/$name'
    | '/_app/_authed/projects/recents'
    | '/_app/_authed/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/logout': {
      id: '/_app/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AppLogoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authed': {
      id: '/_app/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authed/guide': {
      id: '/_app/_authed/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AppAuthedGuideRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/projects/': {
      id: '/_app/_authed/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppAuthedProjectsIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/projects/recents': {
      id: '/_app/_authed/projects/recents'
      path: '/projects/recents'
      fullPath: '/projects/recents'
      preLoaderRoute: typeof AppAuthedProjectsRecentsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/projects/$name': {
      id: '/_app/_authed/projects/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof AppAuthedProjectsNameRouteImport
      parentRoute: typeof AppAuthedRoute
    }
  }
}

interface AppAuthedRouteChildren {
  AppAuthedGuideRoute: typeof AppAuthedGuideRoute
  AppAuthedProjectsNameRoute: typeof AppAuthedProjectsNameRoute
  AppAuthedProjectsRecentsRoute: typeof AppAuthedProjectsRecentsRoute
  AppAuthedProjectsIndexRoute: typeof AppAuthedProjectsIndexRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedGuideRoute: AppAuthedGuideRoute,
  AppAuthedProjectsNameRoute: AppAuthedProjectsNameRoute,
  AppAuthedProjectsRecentsRoute: AppAuthedProjectsRecentsRoute,
  AppAuthedProjectsIndexRoute: AppAuthedProjectsIndexRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
  AppLogoutRoute: typeof AppLogoutRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
  AppLogoutRoute: AppLogoutRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
